spring.application.name=demo

# Direct Public Address (Ab dashboard variables par depend nahi karna parega)
spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:29542/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=TzvHQOjehSdPPhYlFyEVqbzQXhWCyMhI

# Core Database Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# Connection Timeout Fix (Logs mein delay se bachne ke liye)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Railway Server Port Configuration
server.port=${PORT:8080}